# Generated by Django 2.2.12 on 2022-01-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('account_no', models.CharField(max_length=122)),
                ('amount', models.IntegerField()),
                ('city', models.CharField(max_length=122)),
                ('mobile_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=122)),
                ('source_acc_no', models.CharField(max_length=122)),
                ('Current_balance', models.IntegerField()),
                ('money_deposit', models.IntegerField()),
                ('destination_name', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
